/* V3.3 - apresentacao dos modelos corrigidos */
(function(){
 window.recommendation=function(r){
  if(r.isMei)return{key:'mei',title:'MEI: regime híbrido indisponível',text:'O MEI possui regras próprias. Confirme a permanência no SIMEI e as regras específicas aplicáveis.'};
  const valid=r.models.filter(m=>m.valid!==false&&Number.isFinite(m.total));
  if(!valid.length)return{key:'pending',title:'Dados insuficientes para recomendar',text:'Complete os dados pendentes dos regimes aplicáveis. O simulador não usa valores parciais para formar o ranking.'};
  const best=[...valid].sort((a,b)=>a.total-b.total)[0],pending=r.models.filter(m=>m.valid===false).map(m=>m.name),suffix=pending.length?` ${pending.join(' e ')} ${pending.length>1?'foram excluídos':'foi excluído'} do ranking por falta de dados suficientes.`:'';
  return{key:best.key,title:best.name,text:`${best.name} apresenta a menor saída anual estimada entre os modelos validados para ${r.year}. O ranking considera a carga própria da empresa e o custo operacional informado, sem abater o crédito de IBS/CBS pertencente aos clientes B2B. A análise comercial do crédito aparece separadamente.${suffix}`};
 };
 window.renderModels=function(r,rec){
  const info={pure:{sub:'Tudo na guia única do Simples (DAS)',pros:['Guia única e menor complexidade','Sem apuração mensal separada de IBS/CBS','Tende a ser mais simples para vendas a consumidor final'],cons:['Crédito do cliente PJ limitado à parcela de IBS/CBS devida no Simples','Pode perder competitividade em cadeias B2B']},hybrid:{sub:'Simples + IBS/CBS pelo regime regular',pros:['Crédito integral de IBS/CBS para clientes B2B','Aproveita créditos elegíveis das aquisições','Pode preservar competitividade em cadeias empresariais'],cons:['Exige apuração mensal adicional','Aumenta controles fiscais e custo operacional']},presumed:{sub:'Migração total · Lucro Presumido',pros:['Base de IRPJ e CSLL calculada pelas presunções legais','Crédito de IBS/CBS conforme a tributação incidente','Sem teto de faturamento do Simples'],cons:['Contribuição patronal exige base remuneratória própria, separada do Fator R','Despesas operacionais não reduzem a base presumida de IRPJ/CSLL']},real:{sub:'Migração total · Lucro Real',pros:['IRPJ e CSLL partem do lucro contábil ajustado','Despesas dedutíveis já refletidas na DRE reduzem o lucro contábil','Crédito de IBS/CBS conforme a tributação incidente'],cons:['Exige DRE confiável e ajustes fiscais','Prejuízo fiscal e base negativa possuem controles e limites próprios']}};
  $('modelSectionText').textContent='O ranking considera somente modelos com dados suficientes. Crédito gerado ao cliente B2B não é abatido da saída tributária da empresa e é analisado separadamente.';
  const fmt=v=>typeof v==='number'?brl2.format(v):v;
  $('modelCards').innerHTML=r.models.map(m=>{const valid=m.valid!==false,e=r.annualRevenue>0&&valid?m.total/r.annualRevenue:0,rows=[];if(m.key==='pure')rows.push(['DAS',r.das],['IBS/CBS por fora',0],['Parcela de IBS/CBS no DAS',r.embedded]);if(m.key==='hybrid')rows.push(['DAS sem IBS/CBS',r.dasWithout],['IBS/CBS líquido por fora',r.netVat],['Custo operacional informado',r.hybridCompliance]);if(m.key==='presumed')rows.push(['IBS/CBS líquido',r.netVat],['IRPJ + CSLL',r.irpj+r.csll],['Contribuição patronal',r.cppBaseKnown?r.cpp:'Pendente'],['ICMS/ISS residual estimado',r.legacy],['Custo operacional informado',r.fullCompliance]);if(m.key==='real')rows.push(['IBS/CBS líquido',r.netVat],['Lucro contábil antes de IRPJ/CSLL',r.realProfitKnown?r.accountingProfit:'Pendente'],['Base IRPJ após ajustes/compensação',r.realProfitKnown?r.realIrpjBase:'Pendente'],['IRPJ + CSLL',r.realProfitKnown?r.realIrpj+r.realCsll:'Pendente'],['Contribuição patronal',r.cppBaseKnown?r.cpp:'Pendente'],['ICMS/ISS residual estimado',r.legacy],['Custo operacional informado',r.fullCompliance]);const credit=m.key==='pure'?r.pureClientCredit:r.regularClientCredit;return `<article class="modelCard ${valid&&rec.key===m.key?'recommended':''}">${valid&&rec.key===m.key?'<span class="badge">★ RECOMENDADO</span>':!valid?'<span class="scenarioTag">NÃO RANQUEADO</span>':''}<h3>${m.name}</h3><div class="sub">${info[m.key].sub}</div>${m.key!=='pure'&&valid?`<div class="scenarioTag">Cenário ${r.year}</div>`:''}<div class="labelMoney">Saída anual estimada</div><div class="bigMoney">${valid?brl2.format(m.total):'Pendente'}</div><div class="eff">${valid?`Alíquota efetiva ampliada: ${pct1(e)}`:m.validationMessage}</div><div class="modelRows">${rows.map(x=>`<div><span>${x[0]}</span><b>${fmt(x[1])}</b></div>`).join('')}</div><div class="creditBlock"><span>Crédito potencial nas vendas B2B</span><strong>${brl2.format(credit)}</strong><small>${m.key==='pure'?'Limitado à parcela de IBS/CBS devida no Simples':'Crédito do cliente calculado sobre o débito bruto da operação, sem confundir com o IBS/CBS líquido recolhido pelo vendedor'}</small></div><div class="prosBox"><strong>✓ Vantagens</strong><ul>${info[m.key].pros.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="consBox"><strong>! Atenção</strong><ul>${info[m.key].cons.map(x=>`<li>${x}</li>`).join('')}</ul></div></article>`}).join('');
 };
 const oldCompetition=window.renderCompetition;
 window.renderCompetition=function(r){oldCompetition(r);if(r.simpleEligible&&r.extraHybridCost>0&&Number.isFinite(r.breakEvenCapture)){const creditPart=Number.isFinite(r.creditCaptureNeeded)?pct1(r.creditCaptureNeeded):'não aplicável';$('competitionInsight').innerHTML=`O híbrido aumenta a saída própria em <strong>${brl.format(r.extraHybridCost)}</strong> por ano e entrega <strong>${brl.format(r.extraClientCredit)}</strong> adicionais de crédito aos clientes PJ. Isso não reduz o imposto do vendedor. Para neutralizar economicamente a diferença, seria preciso recuperar o equivalente a <strong>${pct1(r.breakEvenCapture)}</strong> das vendas B2B, correspondente a <strong>${creditPart}</strong> do crédito adicional gerado, por meio de preço, margem, retenção ou volume.`}};
 const oldReference=window.renderReferenceComparison;
 window.renderReferenceComparison=function(all){oldReference(all);const table=document.querySelector('.compareTable'),rows=table?.querySelectorAll('tbody tr');if(rows?.[3]?.querySelector('td'))rows[3].querySelector('td').textContent='(−) Créditos sobre aquisições';const ths=document.querySelectorAll('.timeline th');if(ths[4])ths[4].textContent='Créditos nas aquisições';document.querySelectorAll('.mobileCompareRow > span').forEach(el=>{if(el.textContent.includes('Crédito sobre insumos'))el.textContent='Créditos sobre aquisições'})};
 const oldCash=window.renderCash;
 window.renderCash=function(r){oldCash(r);const c=cashMetrics(r),fm=financialMetrics();if($('workingCapitalText')&&!c.notApplicable)$('workingCapitalText').textContent=`Cenário de exposição ao split payment conforme a intensidade informada. Reposição do float e eventual retenção temporária excedente. Reserva considerada: ${brl.format(num('cashReserve'))}.`;if(c.gap>0&&$('financeRateMode')?.value==='auto'&&fm.annualRate==null)$('financingCost').textContent='Definir taxa manual'};
 const cashDescription=document.querySelector('.resultSection.cash .sectionTitle p');if(cashDescription)cashDescription.textContent='Esta seção trata o split payment como cenário de exposição financeira. A intensidade é editável e a implementação efetiva depende da regulamentação e do cronograma aplicável, sem tratar a retenção como nova despesa tributária.';
})();
