/* V3.2 - apresentacao auditada dos modelos e da transicao */
(function(){
 const currentDasShares={
  I:{federal:[.155,.155,.155,.155,.155,.344],local:[.34,.34,.335,.335,.335,0],ipi:[0,0,0,0,0,0]},
  II:{federal:[.14,.14,.14,.14,.14,.255],local:[.32,.32,.32,.32,.32,0],ipi:[.075,.075,.075,.075,.075,.35]},
  III:{federal:[.156,.171,.166,.166,.156,.195],local:[.335,.32,.325,.325,.335,0],ipi:[0,0,0,0,0,0]},
  IV:{federal:[.215,.25,.24,.23,.22,.25],local:[.445,.40,.40,.40,.40,0],ipi:[0,0,0,0,0,0]},
  V:{federal:[.1715,.1715,.1815,.1915,.1715,.20],local:[.14,.17,.19,.21,.235,0],ipi:[0,0,0,0,0,0]}
 };
 function replacementShare(annex,idx){const s=splitShares[annex]||splitShares.I;return ((s.cbs33?.[idx]||0)+(s.ibs33?.[idx]||0))/100}
 function currentConsumptionParts(annex,idx,effective,annualRevenue,das){
  if(annex==='III'&&idx===4&&effective>.1492537){const local=annualRevenue*.05,federal=annualRevenue*Math.max(0,effective-.05)*.2346;return{federal,local,ipi:0,total:federal+local}}
  if(annex==='IV'&&idx===4&&effective>.125){const local=annualRevenue*.05,federal=annualRevenue*Math.max(0,effective-.05)*.3667;return{federal,local,ipi:0,total:federal+local}}
  const s=currentDasShares[annex]||currentDasShares.I,federal=das*(s.federal[idx]||0),local=das*(s.local[idx]||0),ipi=das*(s.ipi[idx]||0);return{federal,local,ipi,total:federal+local+ipi}
 }
 function currentSimpleSnapshot(r){
  if(!r?.simpleEligible)return null;const t=annexBands[r.annex]||annexBands.I;let idx=t.findIndex(x=>r.rbt12<=x[0]);if(idx<0)idx=t.length-1;const [,nominal,deduction]=t[idx],effective=r.rbt12>0?Math.max(0,(r.rbt12*nominal-deduction)/r.rbt12):0,das=r.annualRevenue*effective,parts=currentConsumptionParts(r.annex,idx,effective,r.annualRevenue,das);return{idx,effective,das,...parts}
 }
 function legacyInsideSimple(r){if(!r?.simpleEligible||r.year>=2033)return 0;return Math.max(0,r.das*replacementShare(r.annex,r.sr.idx)-r.embedded)}
 const td=v=>`<strong>${typeof v==='number'?brl2.format(v):v}</strong>`;

 function comparablePending(r){
  return (r?.models||[]).filter(m=>m.valid===false&&(
   m.key==='real'||
   (m.key==='presumed'&&!r.presumedBarred&&!r.presumedOverLimit)||
   ((m.key==='pure'||m.key==='hybrid')&&r.simpleEligible)
  ));
 }
 window.comparablePendingModels=comparablePending;
 window.recommendation=function(r){
  if(r.isMei)return{key:'mei',title:'MEI: regime híbrido indisponível',text:'O MEI possui regras próprias. Confirme a permanência no SIMEI e as regras específicas aplicáveis.'};
  const valid=r.models.filter(m=>m.valid!==false&&Number.isFinite(m.total));
  if(!valid.length)return{key:'pending',title:'Dados insuficientes para recomendar',text:'Complete os dados pendentes dos regimes aplicáveis. O simulador não usa valores parciais para formar o ranking.'};
  const best=[...valid].sort((a,b)=>a.total-b.total)[0],pendingComparable=comparablePending(r);
  if(pendingComparable.length)return{key:'partial',title:'Comparação ainda incompleta',text:`${best.name} tem o menor desembolso entre os modelos atualmente validados, mas ${pendingComparable.map(m=>m.name).join(' e ')} ${pendingComparable.length>1?'ainda não possuem':'ainda não possui'} dados suficientes para uma recomendação final.`};
  const pending=r.models.filter(m=>m.valid===false).map(m=>m.name),suffix=pending.length?` ${pending.join(' e ')} ${pending.length>1?'foram excluídos':'foi excluído'} por impedimento ou não aplicabilidade identificada.`:'';
  const validKeys=valid.map(m=>m.key),regularOnly=validKeys.length>0&&validKeys.every(k=>k==='real'||k==='presumed'),cppPartial=regularOnly&&!r.cppBaseKnown;
  const baseText=cppPartial
   ?`${best.name} apresenta a menor base tributária comparativa entre os modelos validados para ${r.year}. A contribuição patronal não foi informada e, por ser comum ao Lucro Real e ao Lucro Presumido nas premissas adotadas, foi excluída de ambos sem alterar a diferença entre eles. Os valores não representam a carga tributária total projetada.`
   :`${best.name} apresenta o menor desembolso anual estimado entre os modelos validados para ${r.year}. O ranking considera a carga própria da empresa e o custo operacional informado, sem abater o crédito de IBS/CBS pertencente aos clientes B2B.`;
  return{key:best.key,title:best.name,text:`${baseText} A análise comercial do crédito aparece separadamente.${suffix}`};
 };

 window.renderModels=function(r,rec){
  const info={pure:{sub:'Tudo na guia única do Simples (DAS)',pros:['Guia única e menor complexidade','Sem apuração mensal separada de IBS/CBS','Tende a ser mais simples para vendas a consumidor final'],cons:['Crédito do cliente PJ limitado à parcela de IBS/CBS devida no Simples','Pode perder competitividade em cadeias B2B']},hybrid:{sub:'Simples + IBS/CBS pelo regime regular',pros:['Crédito integral de IBS/CBS para clientes B2B','Aproveita créditos elegíveis das aquisições','Pode preservar competitividade em cadeias empresariais'],cons:['Exige apuração mensal adicional','Aumenta controles fiscais e custo operacional']},presumed:{sub:'Migração total · Lucro Presumido',pros:['Base de IRPJ e CSLL calculada pelas presunções legais informadas','Crédito de IBS/CBS conforme a tributação incidente','Despesas operacionais não alteram a base presumida'],cons:['Contribuição patronal exige base remuneratória própria, separada do Fator R','Percentuais de presunção variam conforme a atividade e precisam ser revisados']},real:{sub:'Migração total · Lucro Real',pros:['IRPJ e CSLL partem do lucro contábil ajustado','Salários, pró-labore e despesas dedutíveis refletidos na DRE afetam o lucro contábil','Crédito de IBS/CBS conforme a tributação incidente'],cons:['Exige DRE confiável e ajustes fiscais','Prejuízo fiscal e base negativa possuem controles e limites próprios']}};
  $('modelSectionText').textContent=!r.cppBaseKnown&&!r.simpleEligible
   ?'Lucro Real e Lucro Presumido podem ser comparados sem a contribuição patronal porque ela é tratada como componente comum aos dois. Os valores exibidos excluem a CPP e, portanto, não representam a carga tributária total projetada. Informe a base patronal para completar os totais.'
   :'Os modelos válidos são exibidos do menor para o maior desembolso tributário anual estimado. Modelos pendentes ou não aplicáveis aparecem ao final. Crédito gerado ao cliente B2B não é abatido do desembolso tributário da empresa e é analisado separadamente.';
  const fmt=v=>typeof v==='number'?brl2.format(v):v;
  const ordered=[...r.models].map((m,i)=>({m,i})).sort((a,b)=>{const av=a.m.valid!==false&&Number.isFinite(a.m.total),bv=b.m.valid!==false&&Number.isFinite(b.m.total);if(av!==bv)return av?-1:1;if(av&&bv&&a.m.total!==b.m.total)return a.m.total-b.m.total;return a.i-b.i}).map(x=>x.m);
  const ranked=ordered.filter(m=>m.valid!==false&&Number.isFinite(m.total)),rankMap=new Map(ranked.map((m,i)=>[m.key,i+1]));
  $('modelCards').innerHTML=ordered.map(m=>{const valid=m.valid!==false&&Number.isFinite(m.total),rank=rankMap.get(m.key),e=r.annualRevenue>0&&valid?m.total/r.annualRevenue:0,rows=[];
   if(m.key==='pure')rows.push(['DAS',r.das],['IBS/CBS por fora',0],['Parcela de IBS/CBS no DAS',r.embedded]);
   if(m.key==='hybrid')rows.push(['DAS sem IBS/CBS',r.dasWithout],['IBS/CBS líquido por fora',r.netVat],['Custo operacional informado',r.hybridCompliance]);
   if(m.key==='presumed')rows.push(['IBS/CBS líquido',r.netVat],['Base presumida do IRPJ',r.presumedBaseIR],['Base presumida da CSLL',r.presumedBaseCSLL],['IRPJ + CSLL',r.irpj+r.csll],['Contribuição patronal',r.cppBaseKnown?r.cpp:'Não incluída'],['ICMS/ISS residual estimado',r.legacy],['Custo operacional informado',r.fullCompliance]);
   if(m.key==='real')rows.push(['IBS/CBS líquido',r.netVat],['Lucro contábil antes de IRPJ/CSLL',r.realProfitKnown?r.accountingProfit:'Pendente'],['Base IRPJ após ajustes/compensação',r.realProfitKnown?r.realIrpjBase:'Pendente'],['Base CSLL após ajustes/compensação',r.realProfitKnown?r.realCsllBase:'Pendente'],['IRPJ + CSLL',r.realProfitKnown?r.realIrpj+r.realCsll:'Pendente'],['Contribuição patronal',r.cppBaseKnown?r.cpp:'Não incluída'],['ICMS/ISS residual estimado',r.legacy],['Custo operacional informado',r.fullCompliance]);
   const credit=m.key==='pure'?r.pureClientCredit:r.regularClientCredit,rankLabel=valid?`${rank}º melhor resultado`:'NÃO RANQUEADO',regularPartial=valid&&(m.key==='real'||m.key==='presumed')&&!r.cppBaseKnown;
   return `<article class="modelCard ${valid&&rec.key===m.key?'recommended':''}">${valid&&rec.key===m.key?`<span class="badge">${regularPartial?'★ MELHOR BASE COMPARÁVEL':'★ RECOMENDADO'}</span>`:''}<div class="scenarioTag">${rankLabel}</div><h3>${m.name}</h3><div class="sub">${info[m.key].sub}</div>${m.key!=='pure'&&valid?`<div class="scenarioTag">Cenário ${r.year}</div>`:''}<div class="labelMoney">${regularPartial?'Base anual comparável · sem CPP':'Desembolso anual estimado'}</div><div class="bigMoney">${valid?brl2.format(m.total):'Pendente'}</div><div class="eff">${valid?`${regularPartial?'Base comparativa':'Desembolso'} / faturamento: ${pct1(e)}${regularPartial?' · total projetado incompleto':''}`:m.validationMessage}</div><div class="modelRows">${rows.map(x=>`<div><span>${x[0]}</span><b>${fmt(x[1])}</b></div>`).join('')}</div><div class="creditBlock"><span>Crédito potencial nas vendas B2B</span><strong>${brl2.format(credit)}</strong><small>${m.key==='pure'?'Limitado à parcela de IBS/CBS devida no Simples':'Crédito do cliente calculado sobre o débito bruto da operação, sem confundir com o IBS/CBS líquido recolhido pelo vendedor'}</small></div><div class="prosBox"><strong>✓ Vantagens</strong><ul>${info[m.key].pros.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="consBox"><strong>! Atenção</strong><ul>${info[m.key].cons.map(x=>`<li>${x}</li>`).join('')}</ul></div></article>`
  }).join('');
 };

 window.renderReferenceComparison=function(all){
  const y27=all.find(x=>x.year===2027),y33=all.find(x=>x.year===2033),cur=currentSimpleSnapshot(y27),section=$('vatCompareTitle')?.closest('.resultSection');if(!section)return;
  const old27=legacyInsideSimple(y27),old33=legacyInsideSimple(y33),simple27Consumption=old27+y27.embedded,simple33Consumption=old33+y33.embedded;
  const ipiRow=cur&&cur.ipi>0?`<tr><td>IPI atual dentro do DAS</td><td>${td(cur.ipi)}</td><td class="focus">${td(0)}<small>Regra geral de alíquota zero em 2027; confirmar exceções aplicáveis.</small></td><td>${td(0)}</td></tr>`:'';
  const simpleUnavailable=y27?.eligibility?.status==='over_limit'
   ?`<div class="explainBox"><strong>Simples Nacional não aplicável pelo faturamento informado</strong><p>O RBT12 de ${brl2.format(y27.rbt12)} supera o limite de ${brl2.format(SIMPLES_LIMIT)}. Por isso, Simples Nacional e Simples híbrido ficam fora da decisão prospectiva.</p></div>`
   :`<div class="explainBox"><strong>Referência atual do Simples indisponível</strong><p>A elegibilidade ao Simples não está confirmada, por isso o sistema não inventa uma carga atual dentro do DAS.</p></div>`;
  const simpleTable=cur?`<div class="compareWrap"><h3>Se a empresa permanecer no Simples 100%</h3><table class="compareTable"><thead><tr><th>Componente</th><th>2026 · situação atual</th><th class="focus">2027</th><th>2033</th></tr></thead><tbody><tr><td>DAS total</td><td>${td(cur.das)}</td><td class="focus">${td(y27.das)}</td><td>${td(y33.das)}</td></tr><tr><td>PIS/Cofins atuais dentro do DAS</td><td>${td(cur.federal)}</td><td class="focus"><strong>Extintos</strong></td><td><strong>Extintos</strong></td></tr><tr><td>ICMS/ISS atual ou remanescente dentro do DAS</td><td>${td(cur.local)}</td><td class="focus">${td(old27)}</td><td>${td(old33)}</td></tr>${ipiRow}<tr><td>IBS/CBS dentro do DAS</td><td>${td(0)}<small>As alíquotas teste de 2026 não se aplicam às operações do Simples.</small></td><td class="focus">${td(y27.embedded)}</td><td>${td(y33.embedded)}</td></tr><tr class="strong"><td>Componente de tributos sobre consumo dentro do DAS</td><td>${td(cur.total)}</td><td class="focus">${td(simple27Consumption)}</td><td>${td(simple33Consumption)}</td></tr></tbody></table></div>`:`<div class="explainBox"><strong>Referência atual do Simples indisponível</strong><p>A elegibilidade ao Simples não está confirmada, por isso o sistema não inventa uma carga atual dentro do DAS.</p></div>`;
  const regularTable=`<div class="compareWrap"><h3>Se houver IBS/CBS pelo regime regular</h3><table class="compareTable"><thead><tr><th>Componente</th><th class="focus">2027</th><th>2033</th></tr></thead><tbody><tr><td>PIS/Cofins</td><td class="focus"><strong>Extintos</strong></td><td><strong>Extintos</strong></td></tr><tr><td>IBS/CBS bruto</td><td class="focus">${td(y27.grossVat)}</td><td>${td(y33.grossVat)}</td></tr><tr><td>(−) Créditos sobre aquisições</td><td class="focus">${td(y27.inputCredit)}</td><td>${td(y33.inputCredit)}</td></tr><tr><td>(=) IBS/CBS líquido</td><td class="focus">${td(y27.netVat)}</td><td>${td(y33.netVat)}</td></tr><tr><td>ICMS/ISS residual fora do Simples</td><td class="focus">${td(y27.legacy)}</td><td>${td(y33.legacy)}</td></tr><tr class="strong"><td>Total de tributos sobre consumo fora do Simples</td><td class="focus">${td(y27.netVat+y27.legacy)}</td><td>${td(y33.netVat+y33.legacy)}</td></tr>${y27.simpleEligible?`<tr><td>ICMS/ISS residual dentro do Simples híbrido</td><td class="focus">${td(old27)}</td><td>${td(old33)}</td></tr><tr class="strong"><td>Componente de consumo no híbrido</td><td class="focus">${td(y27.netVat+old27)}</td><td>${td(y33.netVat+old33)}</td></tr>`:''}</tbody></table></div>`;
  section.innerHTML=`<div class="sectionTitle compact"><div><span>A</span><h2 id="vatCompareTitle">Transição dos tributos sobre consumo, sem misturar regimes</h2></div><p>A comparação separa o que está dentro do DAS do que seria apurado pelo regime regular. Assim, a realidade atual não é comparada diretamente com o débito bruto de IBS/CBS de outro regime.</p></div><div class="explainBox"><strong>Leitura correta da transição</strong><p>Em 2026, PIS/Cofins, ICMS e ISS continuam no sistema atual. Em 2027, PIS/Cofins são extintos e substituídos pela CBS; ICMS e ISS continuam integralmente em 2027 e 2028. A redução de ICMS e ISS começa em 2029 e termina em 2033. Para atividades industriais, o IPI deve ser validado separadamente quando houver exceção à regra geral de alíquota zero. <strong>As alíquotas de referência usadas pelo simulador são premissas editáveis de cenário e não devem ser lidas como alíquotas definitivas fixadas para a empresa.</strong></p></div>${simpleTable}${regularTable}<div class="vatSummary" id="vatSummary"></div><div class="timelineWrap"><table class="timeline"><thead></thead><tbody id="timelineBody"></tbody></table></div>`;
 };

 window.renderVatSummary=function(r){
  if(r.isMei){$('vatSummary').innerHTML='<div><span>MEI</span><strong>Regra específica</strong><small>As faixas dos Anexos I a V não são aplicadas ao DAS-MEI.</small></div><div><span>Regime híbrido</span><strong>Não disponível</strong><small>O MEI não pode optar pelo recolhimento regular de IBS/CBS.</small></div>';return}
  const legacySimple=legacyInsideSimple(r),regularTotal=r.netVat+r.legacy;
  $('vatSummary').innerHTML=`<div><span>IBS/CBS líquido no regime regular</span><strong>${brl.format(r.netVat)}</strong><small>Débito bruto de ${brl.format(r.grossVat)} menos créditos estimados de ${brl.format(r.inputCredit)}.</small></div><div><span>ICMS/ISS residual fora do Simples em ${r.year}</span><strong>${brl.format(r.legacy)}</strong><small>${r.year<=2028?'Mantido integralmente na premissa atual.':r.year<2033?'Reduzido conforme a transição constitucional.':'Extinto no regime pleno.'}</small></div><div><span>Total consumo fora do Simples</span><strong>${brl.format(regularTotal)}</strong><small>IBS/CBS líquido + ICMS/ISS residual. No híbrido, o tributo legado remanescente permanece dentro do DAS e é estimado em ${brl.format(legacySimple)}.</small></div>`;
 };

 window.renderTimeline=function(all){
  const table=$('timelineBody')?.closest('table');if(table?.querySelector('thead'))table.querySelector('thead').innerHTML='<tr><th>Ano</th><th>CBS efetiva</th><th>IBS efetivo</th><th>IBS/CBS bruto</th><th>Créditos aquisições</th><th>IBS/CBS líquido</th><th>ICMS/ISS residual fora do Simples</th><th>Total consumo regular</th><th>Melhor desembolso validado</th></tr>';
  $('timelineBody').innerHTML=all.map(r=>{const rec=recommendation(r);if(r.isMei)return`<tr class="${r.year===selectedYear?'selected':''}"><td><b>${r.year}</b></td><td colspan="7">Cálculo regular não aplicável ao DAS-MEI</td><td class="best">${rec.title}</td></tr>`;return`<tr class="${r.year===selectedYear?'selected':''}"><td><b>${r.year}</b></td><td>${pct1(r.rr.cbs*r.factor)}</td><td>${pct1(r.rr.ibs*r.factor)}</td><td>${brl.format(r.grossVat)}</td><td>${brl.format(r.inputCredit)}</td><td>${brl.format(r.netVat)}</td><td>${brl.format(r.legacy)}</td><td>${brl.format(r.netVat+r.legacy)}</td><td class="best">${rec.title}</td></tr>`}).join('');
 };

 const oldCompetition=window.renderCompetition;
 window.renderCompetition=function(r){oldCompetition(r);if(r.simpleEligible&&r.extraHybridCost>0&&Number.isFinite(r.breakEvenCapture)){const creditPart=Number.isFinite(r.creditCaptureNeeded)?pct1(r.creditCaptureNeeded):'não aplicável';$('competitionInsight').innerHTML=`O híbrido aumenta o desembolso próprio em <strong>${brl.format(r.extraHybridCost)}</strong> por ano e entrega <strong>${brl.format(r.extraClientCredit)}</strong> adicionais de crédito aos clientes PJ. Isso não reduz o imposto do vendedor. Para neutralizar economicamente a diferença, seria preciso recuperar o equivalente a <strong>${pct1(r.breakEvenCapture)}</strong> das vendas B2B, correspondente a <strong>${creditPart}</strong> do crédito adicional gerado, por meio de preço, margem, retenção ou volume.`}};
 const oldCash=window.renderCash;
 window.renderCash=function(r){oldCash(r);const c=cashMetrics(r),fm=financialMetrics();if($('workingCapitalText')&&!c.notApplicable)$('workingCapitalText').textContent=c.reserveKnown?`Cenário de exposição ao split payment conforme a intensidade informada. Reposição do float e eventual retenção temporária excedente. Reserva considerada: ${brl.format(c.reserve)}.`:'Cenário de exposição ao split payment calculado. Informe caixa/aplicações para medir o gap de financiamento.';if(c.gap>0&&$('financeRateMode')?.value==='auto'&&fm.annualRate==null)$('financingCost').textContent='Definir taxa manual'};
 const cashDescription=document.querySelector('.resultSection.cash .sectionTitle p');if(cashDescription)cashDescription.textContent='Esta seção trata o split payment como cenário de exposição financeira. A intensidade é editável e a implementação efetiva depende da regulamentação e do cronograma aplicável, sem tratar a retenção como nova despesa tributária.';
})();