window.brmiImport={files:[],candidates:[],docs:[]};

function importMarkup(){return `<section class="panel importPanel" id="importPanel">
 <div class="sectionTitle"><div><span>04</span><div><div class="importTitleTag">V3.1 · preenchimento inteligente</div><h2>Importar dados da empresa</h2></div></div><p>Envie o que tiver disponível. O simulador tenta localizar números úteis, mostra a fonte e pede sua confirmação antes de alimentar o diagnóstico.</p></div>
 <div class="importDrop" id="importDrop" tabindex="0" role="button" aria-label="Selecionar documentos da empresa"><strong>Arraste Balanço, DRE ou relatórios do ERP</strong><p>Você pode combinar vários arquivos. Quanto mais informação consistente houver, menos campos precisarão ser preenchidos manualmente.</p><button id="importChooseBtn" type="button">Selecionar arquivos</button><small>Formatos: PDF com texto pesquisável, CSV, XLS e XLSX · múltiplos arquivos permitidos</small><input id="importFiles" type="file" multiple accept=".pdf,.csv,.xls,.xlsx,text/csv,application/pdf" hidden></div>
 <div class="importPrivacy"><b>🔒</b><div><strong>Processamento local nesta versão.</strong> Os arquivos são lidos no seu navegador para montar as sugestões e não são enviados ao servidor do simulador.</div></div>
 <div id="importProgress" class="importProgress" hidden><span class="importSpinner"></span><div><strong id="importProgressTitle">Analisando documentos...</strong><small id="importProgressText">Identificando estrutura e indicadores.</small></div></div>
 <div id="importFileList" class="importFileList"></div>
 <div id="importSummary" class="importSummary" hidden><div class="importSummaryHead"><div><h3>Informações encontradas</h3><p>Confira a origem e a confiança de cada sugestão antes de usar.</p></div><span id="importSummaryCount" class="importSummaryCount">0 sugestões</span></div><div id="importCandidateGroups" class="importCandidateGroups"></div><div class="importActions"><button class="importApplyHigh" id="importApplyHigh" type="button">Aplicar sugestões de alta confiança</button><button class="importClear" id="importClear" type="button">Limpar documentos</button></div></div>
 <div id="importEmpty" class="importEmpty" hidden>Não encontramos indicadores suficientes nesse arquivo. Você pode manter o preenchimento manual ou adicionar outro documento.</div>
 </section>`}

function loadImportScript(src,test){if(test())return Promise.resolve();return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>reject(new Error('Não foi possível carregar o leitor necessário.'));document.head.appendChild(s)})}
async function ensureXlsx(){await loadImportScript('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js',()=>typeof XLSX!=='undefined')}
async function ensurePdf(){await loadImportScript('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js',()=>typeof pdfjsLib!=='undefined');pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js'}
function normImport(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim()}
function brNum(s){if(typeof s==='number')return s;let x=String(s||'').replace(/R\$|\s/g,'').replace(/[^0-9,.-]/g,'');if(!x)return NaN;if(x.includes(',')&&x.includes('.'))x=x.replace(/\./g,'').replace(',','.');else if(x.includes(','))x=x.replace(',','.');return Number(x)}
function fmtMoney(v){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:2}).format(v)}
function fmtPct(v){return `${Number(v).toLocaleString('pt-BR',{minimumFractionDigits:1,maximumFractionDigits:1})}%`}
function extOf(name){return String(name||'').split('.').pop().toLowerCase()}
function csvRows(text){const first=(text.split(/\r?\n/)[0]||''),sep=(first.match(/;/g)||[]).length>=(first.match(/,/g)||[]).length?';':',';const rows=[];let row=[],cur='',quote=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'){if(quote&&n==='"'){cur+='"';i++}else quote=!quote}else if(c===sep&&!quote){row.push(cur);cur=''}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&n==='\n')i++;row.push(cur);if(row.some(v=>String(v).trim()))rows.push(row);row=[];cur=''}else cur+=c}row.push(cur);if(row.some(v=>String(v).trim()))rows.push(row);return rows}
function rowsText(rows){return rows.map(r=>r.map(v=>String(v??'')).join(' | ')).join('\n')}
async function readImportFile(file){const ext=extOf(file.name);if(ext==='csv'){let text=await file.text();return{rows:csvRows(text),text,type:'CSV'}}if(ext==='xls'||ext==='xlsx'){await ensureXlsx();const ab=await file.arrayBuffer(),wb=XLSX.read(ab,{type:'array'}),rows=[];wb.SheetNames.forEach(n=>{rows.push([`PLANILHA: ${n}`]);rows.push(...XLSX.utils.sheet_to_json(wb.Sheets[n],{header:1,raw:false,defval:''}))});return{rows,text:rowsText(rows),type:'Excel'}}if(ext==='pdf'){await ensurePdf();const ab=await file.arrayBuffer(),pdf=await pdfjsLib.getDocument({data:ab}).promise;let text='';for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p),content=await page.getTextContent();let line='';for(const it of content.items){line+=`${it.str||''} `;if(it.hasEOL){text+=line.trim()+'\n';line=''}}if(line.trim())text+=line.trim()+'\n'}return{rows:null,text,type:'PDF'}}throw new Error('Formato não suportado.')}
function detectDoc(text,rows){const t=normImport(text);if(/ativo circulante/.test(t)&&/passivo/.test(t)&&/patrimonio liquido/.test(t))return'Balanço';if(/receita (bruta|operacional)/.test(t)&&(/lucro bruto|resultado do exercicio|despesas operacionais/.test(t)))return'DRE';if(rows&&/fornecedor|compra|entrada|contas a pagar/.test(t))return'Relatório de compras';if(rows&&/cliente|venda|faturamento|nota fiscal|contas a receber/.test(t))return'Relatório de vendas';if(/folha de pagamento|salarios|pro labore/.test(t))return'Folha / pessoal';return'Relatório'}
function lineValue(text,labels,exclude=[]){const lines=String(text||'').split(/\r?\n/);for(const line of lines){const n=normImport(line);if(!labels.some(x=>n.includes(x))||exclude.some(x=>n.includes(x)))continue;const matches=line.match(/(?:R\$\s*)?-?\d{1,3}(?:\.\d{3})*(?:,\d{1,2})|-?\d+(?:[.,]\d{1,2})?/g)||[];const nums=matches.map(brNum).filter(Number.isFinite);if(nums.length)return nums[nums.length-1]}return null}
function tabularMetrics(rows){if(!rows||rows.length<2)return{};let hi=-1;for(let i=0;i<Math.min(15,rows.length);i++){const h=rows[i].map(normImport);if(h.some(x=>/cliente|cpf|cnpj|documento|fornecedor|valor|total|regime/.test(x))){hi=i;break}}if(hi<0)return{};const headers=rows[hi].map(normImport),data=rows.slice(hi+1).filter(r=>r.some(v=>String(v).trim()));const find=(terms)=>headers.findIndex(h=>terms.some(t=>h.includes(t)));const docIdx=find(['cpf/cnpj','cpf cnpj','documento','cnpj','cpf']),clientIdx=find(['cliente','sacado','tomador']),supplierIdx=find(['fornecedor','emitente']),valueIdx=find(['valor total','valor','total','faturamento','liquido']),regimeIdx=find(['regime','tributacao','simples']);let b2bNum=0,totalNum=0,purchaseTotal=0,regular=0,supTotal=0;data.forEach(r=>{const val=valueIdx>=0?Math.abs(brNum(r[valueIdx])):1;if(!Number.isFinite(val)||val===0)return;if(docIdx>=0){const digits=String(r[docIdx]||'').replace(/\D/g,'');if(digits.length===14)b2bNum+=val;if(digits.length===11||digits.length===14)totalNum+=val}else if(clientIdx>=0){const c=normImport(r[clientIdx]);if(/pj|empresa|juridica|cnpj/.test(c))b2bNum+=val;if(c)totalNum+=val}if(supplierIdx>=0){purchaseTotal+=valueIdx>=0?val:0;supTotal+=val;if(regimeIdx>=0){const rg=normImport(r[regimeIdx]);if(/lucro real|presumido|regular|normal/.test(rg))regular+=val}}
 });const out={};if(totalNum>0)out.b2bPct=100*b2bNum/totalNum;if(purchaseTotal>0)out.purchaseTotal=purchaseTotal;if(supTotal>0&&regimeIdx>=0)out.regularSuppliersPct=100*regular/supTotal;return out}
function candidate(field,label,value,source,confidence,reason,display){if(!Number.isFinite(value))return null;return{field,label,value,source,confidence,reason,display:display||(field.toLowerCase().includes('pct')||field==='realProfitMargin'?fmtPct(value):fmtMoney(value))}}
function analyseImportDoc(file,parsed){const text=parsed.text,type=detectDoc(text,parsed.rows),tab=tabularMetrics(parsed.rows),c=[];const revenue=lineValue(text,['receita bruta','receita operacional bruta','faturamento bruto','faturamento total'],['deducoes','impostos','devolucoes']);const costs=lineValue(text,['cmv','cpv','csp','custo das mercadorias','custo dos produtos','custo dos servicos','custos operacionais']);const cash=lineValue(text,['caixa e equivalentes','disponibilidades']);const profit=lineValue(text,['lucro liquido','resultado liquido','resultado do exercicio']);const payroll=lineValue(text,['folha de pagamento','salarios e encargos','pessoal e encargos']);if(revenue>0)c.push(candidate('rbt12','Faturamento em 12 meses (RBT12)',revenue,file.name,type==='DRE'||type==='Relatório de vendas'?'high':'medium',`Valor localizado em ${type}.`,fmtMoney(revenue)));if(cash>=0&&type==='Balanço')c.push(candidate('cashReserve','Reserva de capital de giro',cash,file.name,'medium','Caixa/disponibilidades encontrado no balanço. Confirme se todo o valor está realmente disponível para capital de giro.',fmtMoney(cash)));if(revenue>0&&profit!==null)c.push(candidate('realProfitMargin','Margem de lucro para cenário de Lucro Real',100*profit/revenue,file.name,'medium','Lucro líquido dividido pela receita é usado apenas como aproximação inicial da margem tributável.',fmtPct(100*profit/revenue)));if(payroll>0)c.push(candidate('monthlyPayroll','Folha mensal estimada',type==='DRE'?payroll/12:payroll,file.name,'medium',type==='DRE'?'Valor anual de pessoal dividido por 12. Confirme a composição válida para o Fator R.':'Valor de folha localizado no relatório. Confirme a periodicidade.',fmtMoney(type==='DRE'?payroll/12:payroll)));if(tab.b2bPct!=null)c.push(candidate('b2bPct','Vendas para clientes PJ (B2B)',tab.b2bPct,file.name,'high','Calculado pelos documentos CPF/CNPJ ou identificação de clientes nas linhas do relatório.',fmtPct(tab.b2bPct)));if(tab.regularSuppliersPct!=null)c.push(candidate('regularSuppliersPct','Fornecedores no regime regular',tab.regularSuppliersPct,file.name,'medium','Calculado pelas linhas que identificam o regime dos fornecedores.',fmtPct(tab.regularSuppliersPct)));return{file:file.name,type,text,candidates:c,purchaseTotal:tab.purchaseTotal||((costs>0&&(type==='DRE'||type==='Relatório de compras'))?costs:null)}}
function buildCrossCandidates(docs,candidates){const revs=candidates.filter(x=>x.field==='rbt12').sort((a,b)=>(a.confidence==='high'?-1:1));const base=revs[0]?.value;if(base>0)docs.forEach(d=>{if(d.purchaseTotal>0){const pct=100*d.purchaseTotal/base;if(pct>=0&&pct<=300)candidates.push(candidate('purchasesPct','Compras/insumos sobre o faturamento',pct,d.file,'medium','Compras/custos encontrados divididos pelo faturamento importado. CMV/CPV/CSP pode não ser igual a compras creditáveis.',fmtPct(pct)))}});return candidates}
function groupedImportCandidates(){return brmiImport.candidates.reduce((a,c,i)=>{c._index=i;(a[c.field]||(a[c.field]=[])).push(c);return a},{})}
function conflictGroup(arr){if(arr.length<2)return false;const vals=arr.map(x=>x.value).filter(Number.isFinite),max=Math.max(...vals),min=Math.min(...vals);return max>0&&(max-min)/max>.05}
function renderImportFiles(){const el=$('importFileList');if(!el)return;el.innerHTML=brmiImport.files.map(f=>`<div class="importFile"><span class="importFileIcon">${f.ext.toUpperCase()}</span><div><strong>${f.name}</strong><small>${f.type||'Aguardando análise'}</small></div><span class="importFileStatus ${f.statusClass||''}">${f.status||'Pendente'}</span></div>`).join('')}
function renderImportCandidates(){const summary=$('importSummary'),empty=$('importEmpty'),groups=groupedImportCandidates(),keys=Object.keys(groups);if(!keys.length){if(summary)summary.hidden=true;if(empty)empty.hidden=false;return}if(empty)empty.hidden=true;if(summary)summary.hidden=false;if($('importSummaryCount'))$('importSummaryCount').textContent=`${brmiImport.candidates.length} sugest${brmiImport.candidates.length===1?'ão':'ões'}`;const root=$('importCandidateGroups');root.innerHTML=keys.map(field=>{const arr=groups[field],conflict=conflictGroup(arr);return `<div class="importGroup"><div class="importGroupHead"><strong>${arr[0].label}</strong><span class="${conflict?'conflict':''}">${conflict?'VALORES DIVERGENTES':'FONTE LOCALIZADA'}</span></div><div class="importCandidates">${arr.map(c=>`<div class="importCandidate"><div class="importCandidateMain"><strong>${c.display}</strong><small>${c.reason}</small><div class="importMeta"><span>${c.source}</span><span class="${c.confidence}">confiança ${c.confidence==='high'?'alta':'média'}</span></div></div><button type="button" data-import-index="${c._index}">Usar este valor</button></div>`).join('')}</div></div>`}).join('');root.querySelectorAll('[data-import-index]').forEach(b=>b.addEventListener('click',()=>applyImportCandidate(Number(b.dataset.importIndex),b)))}
function applyImportCandidate(i,button){const c=brmiImport.candidates[i],el=$(c?.field);if(!c||!el)return;el.value=Math.round(c.value*100)/100;if(c.field==='rbt12'&&$('revenueSync')?.checked&&typeof syncRevenue==='function'){syncRevenue('annual');if(typeof markFieldDerived==='function')markFieldDerived('monthlyRevenue','CALCULADO')}if(c.field==='monthlyRevenue'&&$('revenueSync')?.checked&&typeof syncRevenue==='function'){syncRevenue('monthly');if(typeof markFieldDerived==='function')markFieldDerived('rbt12','CALCULADO')}if(typeof markFieldAuto==='function')markFieldAuto(c.field,'IMPORTADO');if(typeof markDiagnosisDirty==='function')markDiagnosisDirty('import');if(typeof refreshAllFieldStates==='function')refreshAllFieldStates();if(button){button.textContent='Aplicado';button.classList.add('importApplied')}}
async function processImportFiles(files){const list=[...files];if(!list.length)return;brmiImport.files=list.map(f=>({name:f.name,ext:extOf(f.name),status:'Na fila'}));brmiImport.docs=[];brmiImport.candidates=[];renderImportFiles();const progress=$('importProgress');if(progress)progress.hidden=false;for(let i=0;i<list.length;i++){const f=list[i],row=brmiImport.files[i];row.status='Analisando';row.statusClass='';renderImportFiles();if($('importProgressTitle'))$('importProgressTitle').textContent=`Analisando ${f.name}`;if($('importProgressText'))$('importProgressText').textContent=`Arquivo ${i+1} de ${list.length}. Procurando faturamento, clientes, compras, caixa, folha e margem.`;try{const parsed=await readImportFile(f),doc=analyseImportDoc(f,parsed);row.type=doc.type;row.status=doc.candidates.length||doc.purchaseTotal?'Lido':'Sem indicador';row.statusClass=doc.candidates.length||doc.purchaseTotal?'ok':'warn';brmiImport.docs.push(doc);brmiImport.candidates.push(...doc.candidates)}catch(e){row.status='Não lido';row.statusClass='bad';row.type=e.message}renderImportFiles();await new Promise(r=>setTimeout(r,220))}buildCrossCandidates(brmiImport.docs,brmiImport.candidates);if(progress)progress.hidden=true;renderImportCandidates()}
function clearImport(){brmiImport.files=[];brmiImport.docs=[];brmiImport.candidates=[];renderImportFiles();if($('importSummary'))$('importSummary').hidden=true;if($('importEmpty'))$('importEmpty').hidden=true;const inp=$('importFiles');if(inp)inp.value=''}
function initDocumentImport(){const setup=$('setupMount');if(!setup||$('importPanel'))return;setup.insertAdjacentHTML('beforeend',importMarkup());const input=$('importFiles'),drop=$('importDrop'),choose=$('importChooseBtn');choose?.addEventListener('click',e=>{e.stopPropagation();input?.click()});drop?.addEventListener('click',e=>{if(e.target!==choose)input?.click()});drop?.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();input?.click()}});input?.addEventListener('change',()=>processImportFiles(input.files));['dragenter','dragover'].forEach(ev=>drop?.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(ev=>drop?.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('drag')}));drop?.addEventListener('drop',e=>processImportFiles(e.dataTransfer.files));$('importApplyHigh')?.addEventListener('click',()=>{brmiImport.candidates.forEach((c,i)=>{if(c.confidence==='high')applyImportCandidate(i)})});$('importClear')?.addEventListener('click',clearImport)}