window.brmiImport={files:[],candidates:[],docs:[]};

function importMarkup(){return `<section class="panel importPanel" id="importPanel">
 <div class="sectionTitle"><div><span>04</span><div><div class="importTitleTag">V3.2 · preenchimento inteligente</div><h2>Importar dados da empresa</h2></div></div><p>Envie o que tiver disponível. O simulador tenta localizar números úteis, mostra a fonte e pede sua confirmação antes de alimentar o diagnóstico.</p></div>
 <div class="importDrop" id="importDrop" tabindex="0" role="button" aria-label="Selecionar documentos da empresa"><strong>Arraste Balanço, DRE ou relatórios do ERP</strong><p>Você pode combinar vários arquivos. Quanto mais informação consistente houver, menos campos precisarão ser preenchidos manualmente.</p><button id="importChooseBtn" type="button">Selecionar arquivos</button><small>Formatos: PDF com texto pesquisável, CSV, XLS e XLSX · múltiplos arquivos permitidos</small><input id="importFiles" type="file" multiple accept=".pdf,.csv,.xls,.xlsx,text/csv,application/pdf" hidden></div>
 <div class="importPrivacy"><b>🔒</b><div><strong>Processamento local nesta versão.</strong> Os arquivos são lidos no seu navegador para montar as sugestões e não são enviados ao servidor do simulador.</div></div>
 <div id="importProgress" class="importProgress" hidden><span class="importSpinner"></span><div><strong id="importProgressTitle">Analisando documentos...</strong><small id="importProgressText">Identificando estrutura e indicadores.</small></div></div>
 <div id="importFileList" class="importFileList"></div>
 <div id="importSummary" class="importSummary" hidden><div class="importSummaryHead"><div><h3>Informações encontradas</h3><p>Confira a origem e a confiança de cada sugestão antes de usar.</p></div><span id="importSummaryCount" class="importSummaryCount">0 sugestões</span></div><div id="importCandidateGroups" class="importCandidateGroups"></div><div class="importActions"><button class="importApplyHigh" id="importApplyHigh" type="button">Aplicar sugestões de alta confiança</button><button class="importClear" id="importClear" type="button">Limpar documentos</button></div></div>
 <div id="importEmpty" class="importEmpty" hidden>Não encontramos indicadores suficientes nesse arquivo. Você pode manter o preenchimento manual ou adicionar outro documento.</div>
 </section>`}

function loadImportScript(src,test){if(test())return Promise.resolve();return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>reject(new Error('Não foi possível carregar o leitor necessário.'));document.head.appendChild(s)})}
async function ensureXlsx(){await loadImportScript('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js',()=>typeof XLSX!=='undefined')}
async function ensurePdf(){await loadImportScript('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js',()=>typeof pdfjsLib!=='undefined');pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js'}
function normImport(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim()}
function brNum(s){if(typeof s==='number')return s;let x=String(s||'').replace(/R\$|\s/g,'').replace(/[^0-9,.-]/g,'');if(!x)return NaN;if(x.includes(',')&&x.includes('.'))x=x.replace(/\./g,'').replace(',','.');else if(x.includes(','))x=x.replace(',','.');return Number(x)}
function fmtMoney(v){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:2}).format(v)}
function fmtPct(v){return `${Number(v).toLocaleString('pt-BR',{minimumFractionDigits:1,maximumFractionDigits:1})}%`}
function extOf(name){return String(name||'').split('.').pop().toLowerCase()}
function importedCnpjDigits(v){return String(v||'').replace(/\D/g,'')}
function validImportedCnpj(v){const d=importedCnpjDigits(v);if(d.length!==14||/^(\d)\1{13}$/.test(d))return false;const digit=(base,weights)=>{const sum=base.split('').reduce((a,n,i)=>a+Number(n)*weights[i],0),r=sum%11;return r<2?0:11-r};return digit(d.slice(0,12),[5,4,3,2,9,8,7,6,5,4,3,2])===Number(d[12])&&digit(d.slice(0,13),[6,5,4,3,2,9,8,7,6,5,4,3,2])===Number(d[13])}
function formatImportedCnpj(v){const d=importedCnpjDigits(v);return d.length===14?`${d.slice(0,2)}.${d.slice(2,5)}.${d.slice(5,8)}/${d.slice(8,12)}-${d.slice(12)}`:String(v||'')}
function detectImportedCnpj(text,type){if(!/Balanço|DRE/.test(type))return null;const source=String(text||''),re=/\b\d{2}\.?\d{3}\.?\d{3}\/?\d{4}-?\d{2}\b/g,found=new Map();let m;while((m=re.exec(source))){const digits=importedCnpjDigits(m[0]);if(!validImportedCnpj(digits))continue;const context=normImport(source.slice(Math.max(0,m.index-140),Math.min(source.length,m.index+m[0].length+100)));let score=1;if(/cnpj/.test(context))score+=4;if(/entidade|nome empresarial|titular da escrituracao/.test(context))score+=6;if(/signatario|certificado|responsavel legal|contador/.test(context))score-=7;const item=found.get(digits)||{digits,count:0,score:0};item.count++;item.score+=score;found.set(digits,item)}const ranked=[...found.values()].sort((a,b)=>(b.score+b.count*2)-(a.score+a.count*2)),best=ranked[0],second=ranked[1];if(!best||!(best.count>=2||best.score>=8))return null;if(second&&(best.score+best.count*2)<=(second.score+second.count*2)+2)return null;return best.digits}
function csvRows(text){const first=(text.split(/\r?\n/)[0]||''),sep=(first.match(/;/g)||[]).length>=(first.match(/,/g)||[]).length?';':',';const rows=[];let row=[],cur='',quote=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'){if(quote&&n==='"'){cur+='"';i++}else quote=!quote}else if(c===sep&&!quote){row.push(cur);cur=''}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&n==='\n')i++;row.push(cur);if(row.some(v=>String(v).trim()))rows.push(row);row=[];cur=''}else cur+=c}row.push(cur);if(row.some(v=>String(v).trim()))rows.push(row);return rows}
function rowsText(rows){return rows.map(r=>r.map(v=>String(v??'')).join(' | ')).join('\n')}
function pdfItemsToText(items){const rows=[];for(const it of items||[]){const str=String(it.str||'').trim();if(!str)continue;const x=Number(it.transform?.[4]||0),y=Number(it.transform?.[5]||0);let row=rows.find(r=>Math.abs(r.y-y)<=1.5);if(!row){row={y,items:[]};rows.push(row)}row.items.push({x,str})}return rows.sort((a,b)=>b.y-a.y).map(r=>r.items.sort((a,b)=>a.x-b.x).map(i=>i.str).join(' ').replace(/\s+/g,' ').trim()).filter(Boolean).join('\n')}
async function readImportFile(file){const ext=extOf(file.name);if(ext==='csv'){let text=await file.text();return{rows:csvRows(text),text,type:'CSV'}}if(ext==='xls'||ext==='xlsx'){await ensureXlsx();const ab=await file.arrayBuffer(),wb=XLSX.read(ab,{type:'array'}),rows=[];wb.SheetNames.forEach(n=>{rows.push([`PLANILHA: ${n}`]);rows.push(...XLSX.utils.sheet_to_json(wb.Sheets[n],{header:1,raw:false,defval:''}))});return{rows,text:rowsText(rows),type:'Excel'}}if(ext==='pdf'){await ensurePdf();const ab=await file.arrayBuffer(),pdf=await pdfjsLib.getDocument({data:ab}).promise,pages=[];for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p),content=await page.getTextContent();pages.push(pdfItemsToText(content.items))}return{rows:null,text:pages.join('\n'),type:'PDF'}}throw new Error('Formato não suportado.')}
function detectDoc(text,rows){const t=normImport(text),balance=/ativo circulante/.test(t)&&/passivo/.test(t)&&/patrimonio liquido/.test(t),dre=/receitas? (brutas?|operacionais?)/.test(t)&&(/lucro bruto|resultado do exercicio|despesas operacionais|custos e despesas/.test(t));if(balance&&dre)return'Balanço + DRE';if(balance)return'Balanço';if(dre)return'DRE';if(rows&&/fornecedor|compra|entrada|contas a pagar/.test(t))return'Relatório de compras';if(rows&&/cliente|venda|faturamento|nota fiscal|contas a receber/.test(t))return'Relatório de vendas';if(/folha de pagamento|salarios|pro labore/.test(t))return'Folha / pessoal';return'Relatório'}
function importStatementSections(text){const source=String(text||''),bpStart=source.search(/balan[cç]o patrimonial/i),dreStart=source.search(/demonstra[cç][aã]o\s+(?:d[eo]\s+)?resultado/i);return{balance:bpStart>=0?source.slice(bpStart,dreStart>bpStart?dreStart:undefined):source,dre:dreStart>=0?source.slice(dreStart):source}}
function lineValue(text,labels,exclude=[]){const lines=String(text||'').split(/\r?\n/);for(const line of lines){const n=normImport(line);if(!labels.some(x=>n.includes(x))||exclude.some(x=>n.includes(x)))continue;const matches=line.match(/(?:R\$\s*)?-?\d{1,3}(?:\.\d{3})*(?:,\d{1,2})|-?\d+(?:[.,]\d{1,2})?/g)||[];const nums=matches.map(brNum).filter(Number.isFinite);if(nums.length)return nums[nums.length-1]}return null}
function firstLineValue(text,labelGroups){for(const labels of labelGroups){const v=lineValue(text,labels);if(v!=null)return v}return null}
function lastLineValue(text,labels,exclude=[]){const lines=String(text||'').split(/\r?\n/);let found=null;for(const line of lines){const n=normImport(line);if(!labels.some(x=>n.includes(x))||exclude.some(x=>n.includes(x)))continue;const matches=line.match(/(?:R\$\s*)?-?\d{1,3}(?:\.\d{3})*(?:,\d{1,2})|-?\d+(?:[.,]\d{1,2})?/g)||[],nums=matches.map(brNum).filter(Number.isFinite);if(nums.length)found=nums[nums.length-1]}return found}
function lastFirstLineValue(text,labelGroups){for(const labels of labelGroups){const v=lastLineValue(text,labels);if(v!=null)return v}return null}

function tabularMetrics(rows){
 if(!rows||rows.length<2)return{};let hi=-1;
 for(let i=0;i<Math.min(15,rows.length);i++){const h=rows[i].map(normImport);if(h.some(x=>/cliente|cpf|cnpj|documento|fornecedor|valor|total|regime/.test(x))){hi=i;break}}
 if(hi<0)return{};const headers=rows[hi].map(normImport),data=rows.slice(hi+1).filter(r=>r.some(v=>String(v).trim()));
 const find=(terms)=>headers.findIndex(h=>terms.some(t=>h.includes(t)));const docIdx=find(['cpf/cnpj','cpf cnpj','documento','cnpj','cpf']),clientIdx=find(['cliente','sacado','tomador']),supplierIdx=find(['fornecedor','emitente']),valueIdx=find(['valor total','valor','total','faturamento','liquido']),regimeIdx=find(['regime','tributacao','simples']);
 let b2bNum=0,totalNum=0,purchaseTotal=0,regular=0,supTotal=0;
 data.forEach(r=>{const value=valueIdx>=0?Math.abs(brNum(r[valueIdx])):1;if(!Number.isFinite(value)||value===0)return;if(docIdx>=0){const digits=String(r[docIdx]||'').replace(/\D/g,'');if(digits.length===14)b2bNum+=value;if(digits.length===11||digits.length===14)totalNum+=value}else if(clientIdx>=0){const c=normImport(r[clientIdx]);if(/pj|empresa|juridica|cnpj/.test(c))b2bNum+=value;if(c)totalNum+=value}if(supplierIdx>=0){purchaseTotal+=valueIdx>=0?value:0;supTotal+=value;if(regimeIdx>=0){const rg=normImport(r[regimeIdx]);if(/lucro real|presumido|regular|normal/.test(rg))regular+=value}}});
 const out={};if(totalNum>0)out.b2bPct=100*b2bNum/totalNum;if(purchaseTotal>0)out.purchaseTotal=purchaseTotal;if(supTotal>0&&regimeIdx>=0)out.regularSuppliersPct=100*regular/supTotal;return out
}
function candidate(field,label,value,source,confidence,reason,display){if(field==='cnpj'){if(!validImportedCnpj(value))return null}else if(!Number.isFinite(value))return null;return{field,label,value,source,confidence,reason,display:display||(field==='cnpj'?formatImportedCnpj(value):(field.toLowerCase().includes('pct')||field==='realProfitMargin'?fmtPct(value):fmtMoney(value)))}}

function analyseImportDoc(file,parsed){
 const text=parsed.text,type=detectDoc(text,parsed.rows),tab=tabularMetrics(parsed.rows),c=[],sections=importStatementSections(text),balanceDoc=type==='Balanço'||type==='Balanço + DRE',dreDoc=type==='DRE'||type==='Balanço + DRE',bpText=balanceDoc?sections.balance:text,dreText=dreDoc?sections.dre:text,importedCnpj=detectImportedCnpj(text,type);
 const revenue=firstLineValue(dreText,[['receita bruta','receita operacional bruta','faturamento bruto','faturamento total'],['servicos prestados','vendas de mercadorias','receita de vendas'],['receitas operacionais']]);
 const costs=firstLineValue(dreText,[['cmv','cpv','csp','custo das mercadorias','custo dos produtos','custo dos servicos'],['custos das atividades empresariais'],['custos gerais','custos operacionais']]);
 const explicitCash=firstLineValue(bpText,[['caixa e equivalentes'],['disponibilidades'],['caixa bancos']]),cashBox=firstLineValue(bpText,[['caixa geral'],['caixa']]),banks=firstLineValue(bpText,[['bancos conta movimento'],['bancos c/ movimento']]),cash=explicitCash!=null?explicitCash:(((cashBox||0)+(banks||0))||null);
 const investments=firstLineValue(bpText,[['aplicacoes financeiras de liquidez imediata'],['aplicacoes de liquidez imediata'],['equivalentes de caixa'],['aplicacoes financeiras']]);
 const currentAssets=lineValue(bpText,['ativo circulante'],['total do ativo','nao circulante']);
 const currentLiabilities=lineValue(bpText,['passivo circulante'],['nao circulante']);
 const profit=lineValue(dreText,['lucro liquido','resultado liquido','resultado do exercicio','resultado exercicio']);
 const payrollCosts=lineValue(dreText,['custos com pessoal']),payrollExpenses=lineValue(dreText,['despesas com pessoal']),payroll=(payrollCosts||0)+(payrollExpenses||0)||lineValue(dreText,['folha de pagamento','salarios e encargos','pessoal e encargos']);
 const debtCurrent=firstLineValue(bpText,[['emprestimos e financiamentos curto prazo'],['emprestimos e financiamentos cp'],['financiamentos curto prazo']]);
 const debtLong=firstLineValue(bpText,[['emprestimos e financiamentos longo prazo'],['emprestimos e financiamentos lp'],['financiamentos longo prazo']]);
 const debtGeneric=lineValue(bpText,['emprestimos e financiamentos']);
 const debtEnd=(debtCurrent||0)+(debtLong||0)||debtGeneric;
 const interest=firstLineValue(dreText,[['juros sobre emprestimos'],['juros sobre financiamentos'],['encargos de emprestimos'],['encargos financeiros de emprestimos'],['juros e encargos da divida']]);
 const genericFinance=lineValue(dreText,['despesas financeiras'],['receitas financeiras']);
 if(importedCnpj)c.push(candidate('cnpj','CNPJ da empresa',importedCnpj,file.name,'high','CNPJ validado e identificado no cabeçalho da demonstração contábil.',formatImportedCnpj(importedCnpj)));
 if(revenue>0)c.push(candidate('rbt12','Faturamento em 12 meses (RBT12)',revenue,file.name,dreDoc||type==='Relatório de vendas'?'high':'medium',`Valor localizado em ${type}.`,fmtMoney(revenue)));
 if(cash!=null&&cash>=0&&balanceDoc)c.push(candidate('cashAndEquivalents','Caixa e equivalentes',cash,file.name,'high','Caixa/disponibilidades localizado no balanço.',fmtMoney(cash)));
 if(investments>0&&balanceDoc)c.push(candidate('liquidInvestments','Aplicações de liquidez imediata',investments,file.name,'medium','Aplicações financeiras localizadas. Confirme se possuem liquidez imediata.',fmtMoney(investments)));
 if(currentAssets>0&&balanceDoc)c.push(candidate('currentAssets','Ativo circulante',currentAssets,file.name,'high','Total do ativo circulante localizado no balanço.',fmtMoney(currentAssets)));
 if(currentLiabilities>0&&balanceDoc)c.push(candidate('currentLiabilities','Passivo circulante',currentLiabilities,file.name,'high','Total do passivo circulante localizado no balanço.',fmtMoney(currentLiabilities)));
 if(debtEnd>0&&balanceDoc)c.push(candidate('debtEnd','Dívida financeira final',debtEnd,file.name,'medium','Empréstimos e financiamentos CP + LP identificados. Confirme o saldo e a data-base.',fmtMoney(debtEnd)));
 if(interest>0&&dreDoc)c.push(candidate('interestExpense','Juros e encargos da dívida',interest,file.name,'high','Conta específica de juros/encargos de empréstimos ou financiamentos localizada na DRE.',fmtMoney(interest)));
 else if(genericFinance>0&&dreDoc)c.push(candidate('interestExpense','Juros e encargos da dívida',genericFinance,file.name,'low','Somente a conta genérica de despesas financeiras foi localizada. Use apenas após revisar se inclui tarifas, IOF, variação cambial, multas ou itens não ligados à dívida.',fmtMoney(genericFinance)));
 if(revenue>0&&profit!==null)c.push(candidate('realProfitMargin','Margem de lucro para cenário de Lucro Real',100*profit/revenue,file.name,'medium','Lucro líquido dividido pela receita é usado apenas como aproximação inicial da margem tributável.',fmtPct(100*profit/revenue)));
 if(payroll>0)c.push(candidate('monthlyPayroll','Folha mensal estimada',dreDoc?payroll/12:payroll,file.name,'medium',dreDoc?'Valor anual de pessoal dividido por 12. Confirme a composição válida para o Fator R.':'Valor de folha localizado no relatório. Confirme a periodicidade.',fmtMoney(dreDoc?payroll/12:payroll)));
 if(tab.b2bPct!=null)c.push(candidate('b2bPct','Vendas para clientes PJ (B2B)',tab.b2bPct,file.name,'high','Calculado pelos documentos CPF/CNPJ ou identificação de clientes nas linhas do relatório.',fmtPct(tab.b2bPct)));
 if(tab.regularSuppliersPct!=null)c.push(candidate('regularSuppliersPct','Fornecedores no regime regular',tab.regularSuppliersPct,file.name,'medium','Calculado pelas linhas que identificam o regime dos fornecedores.',fmtPct(tab.regularSuppliersPct)));
 return{file:file.name,type,text,candidates:c,cnpj:importedCnpj,purchaseTotal:tab.purchaseTotal||((type==='Relatório de compras'&&costs>0)?costs:null)}
}
function buildCrossCandidates(docs,candidates){const revs=candidates.filter(x=>x.field==='rbt12').sort((a,b)=>(a.confidence==='high'?-1:1));const base=revs[0]?.value;if(base>0)docs.forEach(d=>{if(d.purchaseTotal>0){const p=100*d.purchaseTotal/base;if(p>=0&&p<=300)candidates.push(candidate('purchasesPct','Compras/insumos sobre o faturamento',p,d.file,'medium','Compras/custos encontrados divididos pelo faturamento importado. CMV/CPV/CSP pode não ser igual a compras creditáveis.',fmtPct(p)))}});return candidates}
function groupedImportCandidates(){return brmiImport.candidates.reduce((a,c,i)=>{c._index=i;(a[c.field]||(a[c.field]=[])).push(c);return a},{})}
function conflictGroup(arr){if(arr.length<2)return false;if(arr[0]?.field==='cnpj')return new Set(arr.map(x=>x.value)).size>1;const vals=arr.map(x=>x.value).filter(Number.isFinite),max=Math.max(...vals),min=Math.min(...vals);return max>0&&(max-min)/max>.05}
function renderImportFiles(){const el=$('importFileList');if(!el)return;el.innerHTML=brmiImport.files.map(f=>`<div class="importFile"><span class="importFileIcon">${f.ext.toUpperCase()}</span><div><strong>${f.name}</strong><small>${f.type||'Aguardando análise'}</small></div><span class="importFileStatus ${f.statusClass||''}">${f.status||'Pendente'}</span></div>`).join('')}
function renderImportCandidates(){
 const summary=$('importSummary'),empty=$('importEmpty'),groups=groupedImportCandidates(),keys=Object.keys(groups);if(!keys.length){if(summary)summary.hidden=true;if(empty)empty.hidden=false;return}if(empty)empty.hidden=true;if(summary)summary.hidden=false;if($('importSummaryCount'))$('importSummaryCount').textContent=`${brmiImport.candidates.length} sugest${brmiImport.candidates.length===1?'ão':'ões'}`;
 const root=$('importCandidateGroups');root.innerHTML=keys.map(field=>{const arr=groups[field],conflict=conflictGroup(arr);return `<div class="importGroup"><div class="importGroupHead"><strong>${arr[0].label}</strong><span class="${conflict?'conflict':''}">${conflict?'VALORES DIVERGENTES':'FONTE LOCALIZADA'}</span></div><div class="importCandidates">${arr.map(c=>`<div class="importCandidate"><div class="importCandidateMain"><strong>${c.display}</strong><small>${c.reason}</small><div class="importMeta"><span>${c.source}</span><span class="${c.confidence}">confiança ${c.confidence==='high'?'alta':c.confidence==='medium'?'média':'baixa'}</span></div></div><button type="button" data-import-index="${c._index}">Usar este valor</button></div>`).join('')}</div></div>`}).join('');root.querySelectorAll('[data-import-index]').forEach(b=>b.addEventListener('click',()=>applyImportCandidate(Number(b.dataset.importIndex),b)))
}
function applyImportCandidate(i,button){
 const c=brmiImport.candidates[i],el=$(c?.field);if(!c||!el)return;if(c.field==='cnpj'){el.value=typeof normalizeCnpjInput==='function'?normalizeCnpjInput(c.value):formatImportedCnpj(c.value);if(typeof markFieldAuto==='function')markFieldAuto('cnpj','IMPORTADO');if(button){button.textContent='Aplicado';button.classList.add('importApplied')}if(typeof lookupCnpj==='function')lookupCnpj();return}el.value=Math.round(c.value*100)/100;
 if(c.field==='currentConsumptionTaxAnnual'&&$('currentConsumptionMode')){$('currentConsumptionMode').value='manual';el.readOnly=false}
 if(c.field==='rbt12'&&$('revenueSync')?.checked&&typeof syncRevenue==='function'){syncRevenue('annual');if(typeof markFieldDerived==='function')markFieldDerived('monthlyRevenue','CALCULADO')}
 if(c.field==='monthlyRevenue'&&$('revenueSync')?.checked&&typeof syncRevenue==='function'){syncRevenue('monthly');if(typeof markFieldDerived==='function')markFieldDerived('rbt12','CALCULADO')}
 if(typeof markFieldAuto==='function')markFieldAuto(c.field,c.confidence==='low'?'REVISAR':'IMPORTADO');
 if(typeof financialMetrics==='function')financialMetrics();if(typeof refreshEligibilityUi==='function')refreshEligibilityUi();
 if(typeof markDiagnosisDirty==='function')markDiagnosisDirty('import');if(typeof refreshAllFieldStates==='function')refreshAllFieldStates();if(button){button.textContent='Aplicado';button.classList.add('importApplied')}
}
async function autoLookupImportedCompany(docs){const ids=[...new Set((docs||[]).map(d=>d.cnpj).filter(Boolean))];if(ids.length!==1)return;const raw=ids[0],el=$('cnpj'),status=$('lookupStatus');if(!el)return;const current=importedCnpjDigits(el.value);if(current&&current!==raw){if(status){status.className='status';status.textContent=`O documento contém o CNPJ ${formatImportedCnpj(raw)}, diferente do CNPJ já informado. Revise antes de aplicar.`}return}el.value=typeof normalizeCnpjInput==='function'?normalizeCnpjInput(raw):formatImportedCnpj(raw);if(typeof markFieldAuto==='function')markFieldAuto('cnpj','IMPORTADO');if(brmiImport.lastLookupCnpj===raw)return;brmiImport.lastLookupCnpj=raw;if(typeof lookupCnpj==='function')await lookupCnpj()}
async function processImportFiles(files){
 const list=[...files];if(!list.length)return;brmiImport.files=list.map(f=>({name:f.name,ext:extOf(f.name),status:'Na fila'}));brmiImport.docs=[];brmiImport.candidates=[];renderImportFiles();const progress=$('importProgress');if(progress)progress.hidden=false;
 for(let i=0;i<list.length;i++){const f=list[i],row=brmiImport.files[i];row.status='Analisando';row.statusClass='';renderImportFiles();if($('importProgressTitle'))$('importProgressTitle').textContent=`Analisando ${f.name}`;if($('importProgressText'))$('importProgressText').textContent=`Arquivo ${i+1} de ${list.length}. Procurando faturamento, clientes, compras, caixa, BP, dívida, juros, folha e margem.`;try{const parsed=await readImportFile(f),doc=analyseImportDoc(f,parsed);row.type=doc.type;row.status=doc.candidates.length||doc.purchaseTotal?'Lido':'Sem indicador';row.statusClass=doc.candidates.length||doc.purchaseTotal?'ok':'warn';brmiImport.docs.push(doc);brmiImport.candidates.push(...doc.candidates)}catch(e){row.status='Não lido';row.statusClass='bad';row.type=e.message}renderImportFiles();await new Promise(r=>setTimeout(r,220))}
 buildCrossCandidates(brmiImport.docs,brmiImport.candidates);if(progress)progress.hidden=true;renderImportCandidates();await autoLookupImportedCompany(brmiImport.docs)
}
function clearImport(){brmiImport.files=[];brmiImport.docs=[];brmiImport.candidates=[];renderImportFiles();if($('importSummary'))$('importSummary').hidden=true;if($('importEmpty'))$('importEmpty').hidden=true;const inp=$('importFiles');if(inp)inp.value=''}
function initDocumentImport(){const setup=$('setupMount');if(!setup||$('importPanel'))return;setup.insertAdjacentHTML('beforeend',importMarkup());const input=$('importFiles'),drop=$('importDrop'),choose=$('importChooseBtn');choose?.addEventListener('click',e=>{e.stopPropagation();input?.click()});drop?.addEventListener('click',e=>{if(e.target!==choose)input?.click()});drop?.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();input?.click()}});input?.addEventListener('change',()=>processImportFiles(input.files));['dragenter','dragover'].forEach(ev=>drop?.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(ev=>drop?.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('drag')}));drop?.addEventListener('drop',e=>processImportFiles(e.dataTransfer.files));$('importApplyHigh')?.addEventListener('click',()=>{brmiImport.candidates.forEach((c,i)=>{if(c.confidence==='high')applyImportCandidate(i)})});$('importClear')?.addEventListener('click',clearImport)}
